AYON_TAG_NAME = "AYONdata"
LEGACY_OPENPYPE_TAG_NAME = "openpypeData"

AYON_WORKFILE_TAG_BIN = "AYONdata"
AYON_WORKFILE_TAG_NAME = "workfile"

DEFAULT_SEQUENCE_NAME = "ayonSequence"
DEFAULT_BIN_NAME = "ayonBin"
